name: Python Publish Workflow

on:
  push:
    branches:
      - master
  schedule:
    - cron: '37 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: switch to build branch
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git fetch
        git checkout build
        git merge -X theirs master --allow-unrelated-histories

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Choose the version you need

    - name: Install Dependencies 
      run: |
        pip install -r requirements.txt  # If you have any dependencies

    - name: Run Python Script
      run: |
        python fetch_arxiv.py config.json  # Replace with the actual name of your Python script

    - name: Commit and Push Changes
      run: |
        git add -A
        git commit -m "Auto-generated HTML file"
        git push -f origin build
